linters:
  enable-all: true
  disable:
    - exportloopref # replaced by copyloopvar
    - execinquery # deprecated
    - godox # unwanted
    - gomnd # replaced by mnd
    - tagliatelle # only upstream defined schemas in use
    # TODO
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gosec
    - lll
    - mnd
    - nakedret
    - nestif
    - nilnil
    - noctx
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/scop/wrun)
  gofumpt:
    extra-rules: true
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  uniq-by-line: true
