version: 2

builds:
  - id: wrun
    env:
      - CGO_ENABLED=0
    main: .
    binary: wrun
    goos: [darwin, linux, windows]
    goarch: [amd64, arm, arm64, 386]
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - id: wrun-bin
    format: binary

nfpms:
  - id: wrun-nfpm
    package_name: wrun
    file_name_template: "{{ .ConventionalFileName }}"
    builds: [wrun]
    vendor: Ville Skyttä
    homepage: https://github.com/scop/wrun
    maintainer: Ville Skyttä <ville.skytta@iki.fi>
    description: Download, cache, and run executables, same command for multiple OS/architectures
    license: Apache-2.0
    section: web
    formats: [deb, rpm]
    contents:
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-black-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-committed-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-dprint-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-golangci-lint-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-hadolint-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-ruff-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-shellcheck-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-shfmt-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-terraform-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-tflint-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-trivy-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-typos-args
        file_info:
          mode: 0755
      - src: src/wrun-args.sh
        dst: /usr/bin/wrun-vacuum-args
        file_info:
          mode: 0755
      - src: src/wrun_py/*.py
        dst: /usr/share/wrun/wrun_py/
      - src: src/wrun_py/generators/*.py
        dst: /usr/share/wrun/wrun_py/generators/
      - src: LICENSE
        dst: /usr/share/doc/wrun/copyright
        packager: deb
      - src: LICENSE
        dst: /usr/share/doc/wrun/LICENSE
        type: license
        packager: rpm
      - src: README.md
        dst: /usr/share/doc/wrun/README.md
        packager: deb
      - src: src/wrun_py/generators/README.md
        dst: /usr/share/doc/wrun/README-generators.md
        packager: deb
      - src: README.md
        dst: /usr/share/doc/wrun/README.md
        type: readme
        packager: rpm
      - src: src/wrun_py/generators/README.md
        dst: /usr/share/doc/wrun/README-generators.md
        type: readme
        packager: rpm
    rpm:
      group: Applications/Internet

release:
  ids: [wrun-bin]
  footer: >-
    apt and dnf/yum package repositories are available at
    [Packagecloud](https://packagecloud.io/scop/wrun).

changelog:
  use: github
  filters:
    exclude:
      - ^Merge pull request
