name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: | # setup-go handles Go
            ~/.cache/wrun
            ~/.npm
          key: lint-${{ hashFiles('.lefthook.yaml') }}
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ">=1.22"
          check-latest: true
      - name: Install dependencies
        run: |
          go build -v .
      - name: Run lefthook pre-commit
        run: |
          export PATH=$PWD:$PATH LEFTHOOK_QUIET=meta,execution WRUN_VERBOSE=true
          npm exec --yes -- lefthook run pre-commit --all-files --force --no-tty
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version: ">=1.22"
          check-latest: true
      - run: go test -v ./...
