name: Check generators

on:
  pull_request:
    paths:
      - "cmd/**/*.go"
      - "internal/**/*.go"
      - ".github/workflows/check-generators.yaml"
  push:
    branches:
      - main
    paths:
      - "cmd/**/*.go"
      - "internal/**/*.go"
      - ".github/workflows/check-generators.yaml"
  schedule:
    - cron: "42 0 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run generators
        run: |
          set -euxo pipefail
          rc=0
          tmpfile=$(mktemp --tmpdir wrun-generate-test-XXXXXX)
          trap 'rm -f "$tmpfile"' EXIT
          for gen in black shellcheck terraform; do
            printf "go run . generate "%s" || rc=\$?\n" "$gen" >>"$tmpfile"
          done
          for repo in github pypi; do
            go run . generate "$repo" --help | sed -ne '/^Examples/,/^$/p' | sed -ne '/^wrun generate /s/^wrun \(.*\)/go run . \1 || rc=$?/p' >>"$tmpfile"
          done
          . "$tmpfile"
          exit $rc
