name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: | # setup-go handles Go
            ~/.cache/wrun
            ~/.npm
          key: lint-${{ hashFiles('.lefthook.yaml') }}
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Install dependencies for golangci-lint
        run: |
          go build -v .
      - name: Run lefthook pre-commit
        env:
          CLICOLOR_FORCE: true # lefthook, through github.com/muesli/termenv
          LEFTHOOK_QUIET: meta,execution
          WRUN_VERBOSE: true
        run: |
          export PATH=$PWD:$PATH
          npm exec --yes -- lefthook run pre-commit --all-files --force --no-tty
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
      - run: go test -v ./...
