name: Release

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*.*.*", "!v*-*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod
          check-latest: true
      - uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          args: release ${{ !startsWith(github.ref, 'refs/tags/') && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
      - name: Upload to Packagecloud
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gem install --no-document --user-install --bindir ~/.local/bin package_cloud
          export CLICOLOR_FORCE=1
          ~/.local/bin/package_cloud push ${{ github.repository }}/any/any dist/*.deb
          ~/.local/bin/package_cloud push ${{ github.repository }}/rpm_any/rpm_any dist/*.rpm
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
