name: Release to PyPI

on:
  push:
    tags: ["v*-*"]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Sanity check setup.cfg
        run: |
          grep -x "version = \"${GITHUB_REF#refs/tags/v}\"" pyproject.toml
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-13, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: sanity
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build source distribution
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          set -euxo pipefail
          python3 -m venv venv ; source venv/bin/activate
          python3 -m pip install build~=1.0
          python3 -m build --sdist --outdir wheelhouse
          ls wheelhouse
      - name: Build wheels
        env:
          # With 0.2.1 binaries on macos-13 builder out of the box:
          # > delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.9:
          # > .../wrun_py-0.2.1.post1.data/scripts/wrun has a minimum target of 10.13
          # https://cibuildwheel.pypa.io/en/stable/faq/#macos-library-dependencies-do-not-satisfy-target-macos
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=10.13
          # cibuildwheel has issues building with Python 3.8 on macos-latest (= -14 at time of writing) arm64:
          # https://github.com/pypa/cibuildwheel/issues/1278 (similar, maybe)
          CIBW_SKIP: cp38-macosx_arm64
        run: |
          ${{ !startsWith(matrix.os, 'windows') && 'set -euxo pipefail ; python3 -m venv venv ; source venv/bin/activate' || '' }}
          python3 -m pip install cibuildwheel~=2.16
          cibuildwheel
          ls wheelhouse
      - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: dist-files-${{ matrix.os }}
          path: wheelhouse/*
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          pattern: dist-files-*
          merge-multiple: true
          path: dist
      - run: ls dist
      - uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6 # v1.10.0
