name: Release

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*.*.*", "!v*-*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.22"
          check-latest: true
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release ${{ !startsWith(github.ref, 'refs/tags/') && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
      - name: Upload to Packagecloud
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gem install --no-document --user-install --bindir ~/.local/bin package_cloud
          export CLICOLOR_FORCE=1
          ~/.local/bin/package_cloud push ${{ github.repository }}/any/any dist/*.deb
          ~/.local/bin/package_cloud push ${{ github.repository }}/rpm_any/rpm_any dist/*.rpm
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
